#ifndef __KEYBOARD_H__
#define __KEYBOARD_H__

typedef enum {
	_KEYBOARD_T1,
	_KEYBOARD_T2,
	_KEYBOARD_T3,
	_KEYBOARD_T4,
	_KEYBOARD_T5,
	_KEYBOARD_T6,
	_KEYBOARD_T7,
	_KEYBOARD_T8,
	_KEYBOARD_T9,
	_KEYBOARD_T10,
	_KEYBOARD_T11,
	_KEYBOARD_T12,
	_KEYBOARD_T13,
	_KEYBOARD_T14,
	_KEYBOARD_T15,
	_KEYBOARD_MAX,
}KeyBoard_Type;


#endif